// Generated by CoffeeScript 1.12.2
(function() {
  var i, update_vis, years;

  years = ['1995', '2000', '2005', '2010', '2015'];

  update_vis = function(year) {
    window.slope.update(year);
    return window.map.update(year);
  };

  d3.select('#a-years').selectAll('.btn').on('click', function() {
    var btn, year;
    btn = d3.select(this);
    year = btn.attr('data-year');
    d3.selectAll('#a-years .btn').classed('active', false);
    btn.classed('active', true);
    return update_vis(year);
  });

  d3.select('#play').on('click', function() {
    return play();
  });

  i = 0;

  this.play = function() {
    var year;
    if (i < 5) {
      d3.select('#play i').classed('fa-play-circle', false);
      d3.select('#play i').classed('fa-play-circle-o', true);
      year = years[i];
      $('[data-year]').removeClass('active', false);
      $("[data-year=" + year + "]").addClass('active', true);
      update_vis(years[i]);
      i++;
      return window.setTimeout(play, 2000);
    } else {
      i = 0;
      d3.select('#play i').classed('fa-play-circle', true);
      return d3.select('#play i').classed('fa-play-circle-o', false);
    }
  };

}).call(this);

//# sourceMappingURL=animation.js.map
