// Generated by CoffeeScript 1.12.2
(function() {
  var colors, draw, duration, format, height, padding, svg, width, x_scale, y_axis, y_scale;

  svg = d3.select('svg#slope');

  height = svg.attr('height');

  width = svg.attr('width');

  padding = 20;

  duration = 1000;

  format = d3.format(',%');

  colors = ['#e41a1c', '#377eb8', '#4daf4a', '#984ea3'];

  x_scale = d3.scale.linear().domain([0, 1]).range([padding + 80, width - 250]);

  y_scale = d3.scale.linear().domain([0, 1]).range([height - padding, padding]);

  y_axis = d3.svg.axis().scale(y_scale).orient('left').tickFormat(format).ticks(4);

  svg.append('text').attr('x', x_scale(0)).attr('y', height - 5).attr('text-anchor', 'middle').text('Immunization');

  svg.append('text').attr('x', x_scale(1)).attr('y', height - 5).attr('text-anchor', 'middle').text('Treatment');

  svg.append('g').attr('class', 'y axis').attr('transform', 'translate(' + (padding + 15) + ',0)').call(y_axis);

  draw = function(data) {
    var g, hide, legend, legend_svg, newxpos, s, series, show, xpos;
    legend_svg = d3.select("#legend");
    series = d3.nest().key(function(d) {
      return d['Income Group'];
    }).rollup(function() {
      return {};
    }).entries(data);
    legend = legend_svg.append('g').attr('class', 'legend');
    s = legend.selectAll('.series').data(series).enter().insert('g').attr('class', 'series');
    s.insert('text').text(function(d) {
      return d.key;
    }).attr('x', 15).attr('y', 15);
    s.insert('circle').attr('cx', 0).attr('cy', 10).attr('r', 8).attr('fill', function(d, i) {
      return colors[i];
    });
    xpos = 0;
    newxpos = 15;
    s.attr('transform', function(d, i) {
      var length;
      xpos = newxpos;
      length = d3.select(this).select('text').node().getComputedTextLength() + 50;
      newxpos += length;
      return "translate(" + xpos + ", 5)";
    });
    g = svg.selectAll('g.slope-group').data(data, function(d) {
      return d['Income Group'];
    }).enter().append('g').attr('class', 'slope-group');
    g.insert('circle').attr('class', 'start').attr('cx', function(d) {
      return x_scale(0);
    }).attr('cy', function(d) {
      return y_scale(d.Immunization);
    }).attr('fill', function(d, i) {
      return colors[i];
    }).attr('r', 6);
    g.insert('circle').attr('class', 'end').attr('cx', function(d) {
      return x_scale(1);
    }).attr('cy', function(d) {
      return y_scale(d.Treatment);
    }).attr('fill', function(d, i) {
      return colors[i];
    }).attr('r', 6);
    g.insert('line').attr('class', 'slope').attr('x1', x_scale(0)).attr('x2', x_scale(1)).attr('y1', function(d) {
      return y_scale(d.Immunization);
    }).attr('y2', function(d) {
      return y_scale(d.Treatment);
    }).attr('stroke', function(d, i) {
      return colors[i];
    }).attr('stroke-width', 6);
    g.insert('text').attr('class', 'start').text(function(d) {
      return format(d.Immunization);
    }).attr('text-anchor', 'end').attr('x', x_scale(0) - 10).attr('y', function(d) {
      return y_scale(d.Immunization) + 5;
    });
    g.insert('text').attr('class', 'end').text(function(d) {
      return format(d.Treatment);
    }).attr('x', x_scale(1) + 10).attr('y', function(d) {
      return y_scale(d.Treatment) + 5;
    });
    show = function() {
      return d3.select(this).selectAll('text.start, text.end').classed('show', true);
    };
    hide = function() {
      return d3.select(this).selectAll('text.start, text.end').classed('show', false);
    };
    d3.selectAll('g.slope-group').on('mouseover', show);
    d3.selectAll('g.slope-group').on('mouseout', hide);
    return this.slope.update = function(year) {
      var d, filtered, key_fn;
      filtered = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = data.length; j < len; j++) {
          d = data[j];
          if (d.Year === year) {
            results.push(d);
          }
        }
        return results;
      })();
      key_fn = function(d) {
        return d['Income Group'];
      };
      svg.selectAll('circle.start').data(filtered, key_fn).transition().duration(duration).ease('variable').attr('cx', function(d) {
        return x_scale(0);
      }).attr('cy', function(d) {
        return y_scale(d.Immunization);
      });
      svg.selectAll('circle.end').data(filtered, key_fn).transition().duration(duration).ease('variable').attr('cx', function(d) {
        return x_scale(1);
      }).attr('cy', function(d) {
        return y_scale(d.Treatment);
      });
      svg.selectAll('line.slope').data(filtered, key_fn).transition().duration(duration).ease('variable').attr('y1', function(d) {
        return y_scale(d.Immunization);
      }).attr('y2', function(d) {
        return y_scale(d.Treatment);
      });
      svg.selectAll('text.start').data(filtered, key_fn).text(function(d) {
        return format(d.Immunization);
      }).attr('y', function(d) {
        return y_scale(d.Immunization) + 5;
      });
      return svg.selectAll('text.end').data(filtered, key_fn).text(function(d) {
        return format(d.Treatment);
      }).attr('y', function(d) {
        return y_scale(d.Treatment) + 5;
      });
    };
  };

  d3.csv('income_group.csv', draw);

}).call(this);

//# sourceMappingURL=slope.js.map
